#!/bin/bash
# Defines useful functions and runs tests

# TestStart <name>
#     - Call this before a test, passing the test name as the first argument
#
# TestEnd <status> [msgword1 ...]
#     - Call this at the end of a test, with the exit status as the first
#       argument, and a message for the remaining arguments
#
#       ASCII SUB characters (032) in the message will be replaced with
#       newlines.
#
# Test <file> [<file> ...]
#     - Sources the filenames passed as arguments, running each as a single
#       test. The exit value of the file is the result value of the test. If
#       it is non-zero, the test is considered failed, and the output of the
#       file (both stdout and stderror) is printed as the error message.
#
# FinishTests
#     - Reports a summary of the tests that were run, and then exists with
#       status of 1 if any failed, or 0 if all passed.
#
#       However, if any positional parameters are in scope when this file is
#       sourced, FinishTests will instead act as a wrapper script, and exec
#       those positional parameters.


#
# Convenience functions for the actual tests:
#
#   test_check-perms <var_name> <filename> <uid> <gid> <mode>
#     - Checks the ownership and mode of the specified file. Sets the variable
#       named <var_name> to 'false' if the ownerships and modes differ from
#       from what is specified, and leaves its current value alone if the
#       ownerships and modes match.
#
#       An error message will be printed to stdout if ownerships or modes are
#       incorrect.

num_success=0
num_fail=0

red=$'\033[31m'
green=$'\033[32m'
blue=$'\033[34m'
darkgreen=$'\033[36m'
normal=$'\033[0m'

cat <<- EOF
	${darkgreen}=======================${normal}
	${darkgreen}    Starting Tests     ${normal}
	${darkgreen}=======================${normal}
	EOF

SAVE_FOR_LATER_JWGQL0O8="$@"

function TestStart () {
    cat  <<-EOF
	${blue}Running Test:${normal} $*
	EOF
}

function TestEnd () {
  declare -g num_success num_fail

  ret_val=$1
  shift 1

  if [[ $ret_val == 0 ]]; then
    num_success=$(( $num_success + 1 ))

    cat  <<-EOF
	${green}Test Succeeded!${normal}
	${green}Message/Output:${normal}
	EOF
    echo "$*" | tr '\32' '\n' | fold -s -w 76 | sed 's/^/  /'
  else
    num_fail=$(( $num_fail + 1 ))

    cat  <<-EOF
	${red}Test failed with status:${normal} $ret_val
	${red}Message/Output:${normal}
	EOF
    echo "$*" | tr '\32' '\n' | fold -s -w 76 | sed 's/^/  /'
  fi

  # For the newline
  echo
}

function Test () {
  for file in "$@"; do
    TestStart "$file"

    # If it is a directory, change to that directory
    dir="."
    if [[ -d $file ]]; then
      dir="$file"
    fi

    filename="$dir/$file"
    if ! [[ -a $filename ]]; then
      TestEnd 1 "Test file \`$filename' does not exist!"
    elif ! [[ -f $filename ]]; then
      TestEnd 1 "Test file \`$filename' is not a regular file!"
    elif ! [[ -r $filename ]]; then
      TestEnd 1 "Test file \`$filename' cannot be read!"
    else
      cd "$dir"
      set -o pipefail
      err_msg=$(source "$file" 2>&1 | tr '\n' '\32')
      TestEnd $? $err_msg
      set +o pipefail
      cd $OLDPWD
    fi
  done
}

function FinishTests () {
  declare -g num_success num_fail

  cat <<-EOF
	${darkgreen}=======================${normal}
	${darkgreen}Tests finished running:${normal}
	${darkgreen}=======================${normal}
	$num_success ${green}succeeded${normal}
	$num_fail ${red}failed${normal} 
	EOF

  if [[ $SAVE_FOR_LATER_JWGQL0O8 ]]; then
    exec "$SAVE_FOR_LATER_JWGQL0O8"
  else
    if [[ $num_fail != 0 ]]; then
      exit 1
    else
      exit 0
    fi
  fi
}


## Convenience Functions for Tests:
function test_check-perms () {
  for v in var_name file uid gid mode; do
    declare $v="$1"

    if [[ -z $1 ]]; then
      echo "Test Script Error!: $v unset in test_check-perms()"
      exit 1
    fi

    shift 1
  done

  declare test_succeeded=$var_name

  actual_uid=$(stat -c '%u' $file)
  actual_gid=$(stat -c '%g' $file)
  actual_mode=$(stat -c '%a' $file)

  if [[ $actual_uid != $uid ]]; then
    declare -g $test_succeeded=false
    echo "$file was not set to the correct user; should be $uid, is $actual_uid"
    echo
  fi

  if [[ $actual_gid != $gid ]]; then
    declare -g $test_succeeded=false
    echo "$file was not set to the correct group; should be $gid, is $actual_gid"
    echo
  fi

  if [[ $actual_mode != $mode ]]; then
    declare -g $test_succeeded=false
    echo "$file was not set to the correct mode; should be $mode, is $actual_mode"
    echo
  fi
}
