#!/bin/bash
test_succeeded=true

if . ../check-s3-creds; then
  #   SEE MAN PAGE FOR S3CMD; TRAILING SLASHES ARE SIGNIFICANT
  s3cmd sync ./originals/ s3://"$S3_TEST_PATH"/s3-sync/

  EXPAND_S3_FOLDERS="  $S3_TEST_PATH/s3-sync/|./comparedir"
  EXPAND_S3_FOLDERS+=" $S3_TEST_PATH/s3-sync/|./newdir/comparedir"
  EXPAND_S3_FOLDERS+=" $S3_TEST_PATH/s3-sync|./parent"
  EXPAND_S3_FOLDERS+="  $S3_TEST_PATH/s3-sync|./newdir/parent"
  EXPAND_S3_FOLDERS+=" $S3_TEST_PATH/s3-sync/|./pcomparedir[23.24]"
  EXPAND_S3_FOLDERS+=" |./nonexist1"
  EXPAND_S3_FOLDERS+=" $S3_TEST_PATH/nonexist2|"
  EXPAND_S3_FOLDERS+=" $S3_TEST_PATH/nonexist3"
  EXPAND_S3_FOLDERS+=" $S3_TEST_PATH/nonexist4/|"
  EXPAND_S3_FOLDERS+=" $S3_TEST_PATH/nonexist5/"
  export EXPAND_S3_FOLDERS

  if ! ../../s3-expand true; then
    test_succeeded=false
    echo "ERROR: s3-expand exited."
  else
    # Check File Creation
    for file in ./comparedir ./newdir ./newdir/comparedir ./parent ./newdir/parent; do
      if ! [[ -a $file ]]; then
        test_succeeded=false
        echo "ERROR: $file was not created."
      fi
    done

       REGEX='^\.$'
    REGEX+='\|^./originals'
    REGEX+='\|^./s3-sync$'
    REGEX+='\|^./newdir$'
    REGEX+='\|^./newdir/comparedir'
    REGEX+='\|^./newdir/parent$'
    REGEX+='\|^./newdir/parent/s3-sync'
    REGEX+='\|^./parent$'
    REGEX+='\|^./parent/s3-sync'
    REGEX+='\|^./comparedir'
    REGEX+='\|^./pcomparedir'
    for file in $(find . | grep -v "$REGEX"); do
      test_succeeded=false
        echo "ERROR: $file should not have been created."
    done

    # Find the defaults:
    uid=$(id -u)         
    gid=$(id -g)         
                     
    for dir in ./comparedir ./newdir/comparedir ./parent/s3-sync ./newdir/parent/s3-sync; do 
      for file in $(ls $dir);do
        if ! diff ./originals/$file $dir/$file; then
          test_succeeded=false
          cat <<-EOF
	ERROR: S3 sync expansion not performed correctly:
	  Correct Contents of '$dir/$file':
	$(<./originals/$file)
	  Found Contents:
	$(<$dir/$file)

	EOF
        fi

        mode=$(stat -c%a "./originals/$file")
        test_check-perms test_succeeded "$dir/$file" $uid $gid $mode
      done
    done

    for dir in ./pcomparedir; do 
      for file in $(ls $dir);do
        if ! diff ./originals/$file $dir/$file; then
          test_succeeded=false
          cat <<-EOF
	ERROR: S3 sync expansion not performed correctly:
	  Correct Contents of '$dir/$file':
	$(<./originals/$file)
	  Found Contents:
	$(<$dir/$file)

	EOF
        fi

        mode=$(stat -c%a "./originals/$file")
        test_check-perms test_succeeded "$dir/$file" 23 24 $mode
      done
    done
  fi
else
  test_succeeded=false
fi

$test_succeeded
