#!/bin/bash
test_succeeded=true

if . ../check-s3-creds; then
  #   SEE MAN PAGE FOR S3CMD; TRAILING SLASHES ARE SIGNIFICANT
  s3cmd sync ./originals/ s3://"$S3_TEST_PATH"/s3-sync/

  export EXPAND_S3_FOLDERS="$S3_TEST_PATH/s3-sync/|./comparedir $S3_TEST_PATH/s3-sync/|./newdir/comparedir $S3_TEST_PATH/s3-sync|./parent  $S3_TEST_PATH/s3-sync|./newdir/parent |./nonexist1 $S3_TEST_PATH/nonexist2| $S3_TEST_PATH/nonexist3 $S3_TEST_PATH/nonexist4/| $S3_TEST_PATH/nonexist5/"

  if ! ../../expand.sh true; then
    test_succeeded=false
    echo "ERROR: expand.sh exited."
  else
    # Check File Creation
    for file in ./comparedir ./newdir ./newdir/comparedir ./parent ./newdir/parent; do
      if ! [[ -a $file ]]; then
        test_succeeded=false
        echo "ERROR: $file was not created."
      fi
    done

    for file in $(find . | grep -v '^\.$\|^./originals\|^./newdir$\|^./newdir/comparedir\|\|^./newdir/parent$\|^./newdir/parent/s3-sync\|^./s3-sync$\|^./parent$\|^./parent/s3-sync\|^./comparedir'); do
      test_succeeded=false
        echo "ERROR: $file should not have been created."
    done

    for dir in ./comparedir ./newdir/comparedir ./parent/s3-sync ./newdir/parent/s3-sync; do 
      for file in $(ls $dir);do
        if ! diff ./originals/$file $dir/$file; then
          test_succeeded=false
          cat <<-EOF
	ERROR: S3 sync expansion not performed correctly:
	  Correct Contents of '$dir/$file':
	$(<./originals/$file)
	  Found Contents:
	$(<$dir/$file)

	EOF
        fi
      done
    done
  fi
else
  test_succeeded=false
fi

$test_succeeded
