#!/bin/bash
test_succeeded=true

if . ../check-s3-creds; then
  # First, prepare the testing environment
  for file in testfileA testfileB; do
    s3cmd put ./$file s3://"$S3_TEST_PATH"/$file
  done

  export EXPAND_S3_FILES="$S3_TEST_PATH/testfileA|./fileA $S3_TEST_PATH/testfileB|./newdir/fileB |./nonexist1 $S3_TEST_PATH/nonexist2| $S3_TEST_PATH/nonexist3"

  if ! ../../s3-expand true; then
    test_succeeded=false
    echo "ERROR: s3-expand exited."
  else
    # Check File Creation
    for file in ./fileA ./newdir ./newdir/fileB; do
      if ! [[ -a $file ]]; then
        test_succeeded=false
        echo "ERROR: $file was not created."
      fi
    done

    for file in $(find . | grep -v '^\.$\|^./testfileA$\|^./testfileB$\|^./fileA$\|^./newdir$\|^./newdir/fileB$\|^./s3-files$'); do
      test_succeeded=false
        echo "ERROR: $file should not have been created."
    done

    # Check File Contents

    if ! diff ./testfileA ./fileA; then
      test_succeeded=false
      cat <<-EOF
	ERROR: S3 file expansion not performed correctly:
	  Correct Contents of './fileA':
	$(<./testfileA)
	  Found Contents:
	$(<./fileA)

	EOF
    fi
    
    if ! diff ./testfileB ./newdir/fileB; then
      test_succeeded=false
      cat <<-EOF
	ERROR: S3 file expansion not performed correctly:
	  Correct Contents of './fileB':
	$(<./testfileB)
	  Found Contents:
	$(<./newdir/fileB)

	EOF
    fi
  fi
else
  test_succeeded=false
fi

$test_succeeded
