#!/bin/bash
test_succeeded=true

if . ../check-s3-creds; then
  # First, prepare the testing environment
  for file in testfileA testfileB testfileC; do
    s3cmd put ./$file s3://"$S3_TEST_PATH"/$file
  done

  EXPAND_S3_FILES=" $S3_TEST_PATH/testfileA|./fileA"
  EXPAND_S3_FILES+=" $S3_TEST_PATH/testfileB|./newdir/fileB"
  EXPAND_S3_FILES+=" $S3_TEST_PATH/testfileC|./newdir2/"
  EXPAND_S3_FILES+=" |./nonexist1"
  EXPAND_S3_FILES+=" $S3_TEST_PATH/nonexist2|"
  EXPAND_S3_FILES+=" $S3_TEST_PATH/nonexist3"
  export EXPAND_S3_FILES

  if ! ../../s3-expand true; then
    test_succeeded=false
    echo "ERROR: s3-expand exited."
  else
    # Check File Creation
    for file in ./fileA ./newdir ./newdir/fileB; do
      if ! [[ -a $file ]]; then
        test_succeeded=false
        echo "ERROR: $file was not created."
      fi
    done

    REGEX='^\.$'
    REGEX+='\|^./testfileA$'
    REGEX+='\|^./testfileB$'
    REGEX+='\|^./testfileC$'
    REGEX+='\|^./fileA$'
    REGEX+='\|^./newdir$'
    REGEX+='\|^./newdir/fileB$'
    REGEX+='\|^./newdir2$'
    REGEX+='\|^./newdir2/testfileC$'
    REGEX+='\|^./s3-files$'
    for file in $(find . | grep -v $REGEX); do
      test_succeeded=false
        echo "ERROR: $file should not have been created."
    done

    # Check File Contents

    if ! diff ./testfileA ./fileA; then
      test_succeeded=false
      cat <<-EOF
	ERROR: S3 file expansion not performed correctly:
	  Correct Contents of './fileA':
	$(<./testfileA)
	  Found Contents:
	$(<./fileA)

	EOF
    fi
    
    if ! diff ./testfileB ./newdir/fileB; then
      test_succeeded=false
      cat <<-EOF
	ERROR: S3 file expansion not performed correctly:
	  Correct Contents of './fileB':
	$(<./testfileB)
	  Found Contents:
	$(<./newdir/fileB)

	EOF
    fi
  fi
else
  test_succeeded=false
fi

$test_succeeded
