#!/bin/bash
test_succeeded=true

if . ../check-s3-creds; then
  # First, prepare the testing environment
  cd originals
  tar cf ../s3-tars.tar *
  cd ..
  s3cmd put ./s3-tars.tar s3://"$S3_TEST_PATH"/s3-tars.tar

  EXPAND_S3_TARS="  $S3_TEST_PATH/s3-tars.tar|./comparedir"
  EXPAND_S3_TARS+="  $S3_TEST_PATH/s3-tars.tar|./pcomparedir[23]"
  EXPAND_S3_TARS+="  $S3_TEST_PATH/s3-tars.tar|./p2comparedir/[24.25]"
  EXPAND_S3_TARS+=" $S3_TEST_PATH/s3-tars.tar|./newdir/comparedir"
  EXPAND_S3_TARS+=" $S3_TEST_PATH/s3-tars.tar|./newdir/pcomparedir/[26]"
  EXPAND_S3_TARS+=" $S3_TEST_PATH/s3-tars.tar|./newdir/p2comparedir[27.28]"
  EXPAND_S3_TARS+=" $S3_TEST_PATH/s3-tars.tar|./newdir2/comparedir/"
  EXPAND_S3_TARS+=" |./nonexist1"
  EXPAND_S3_TARS+=" $S3_TEST_PATH/nonexist2.tar|"
  EXPAND_S3_TARS+=" $S3_TEST_PATH/nonexist3"
  export EXPAND_S3_TARS

  if ! ../../s3-expand true; then
    test_succeeded=false
    echo "ERROR: s3-expand exited."
  else
    # Check File Creation
    for file in ./comparedir ./newdir ./newdir/comparedir ; do
      if ! [[ -a $file ]]; then
        test_succeeded=false
        echo "ERROR: $file was not created."
      fi
    done

    REGEX='^\.$'
    REGEX+='\|^./originals'
    REGEX+='\|^./newdir$'
    REGEX+='\|^./newdir/comparedir'
    REGEX+='\|^./newdir/pcomparedir'
    REGEX+='\|^./newdir/p2comparedir'
    REGEX+='\|^./newdir2$'
    REGEX+='\|^./newdir2/comparedir'
    REGEX+='\|^./s3-tars$'
    REGEX+='\|^./s3-tars.tar$'
    REGEX+='\|^./comparedir'
    REGEX+='\|^./pcomparedir'
    REGEX+='\|^./p2comparedir'
    for file in $(find . | grep -v "$REGEX"); do
      test_succeeded=false
        echo "ERROR: $file should not have been created."
    done

    for dir in ./comparedir ./newdir/comparedir ./newdir2/comparedir; do 
      for file in $(ls $dir);do
        if ! diff ./originals/$file $dir/$file; then
          test_succeeded=false
          cat <<-EOF
	ERROR: S3 file expansion not performed correctly:
	  Correct Contents of '$dir/$file':
	$(<./originals/$file)
	  Found Contents:
	$(<$dir/$file)

	EOF
        fi
      done
    done

    # Permissions check are needed for these
    dir="./pcomparedir"
    for file in $(ls $dir);do
      if ! diff ./originals/$file $dir/$file; then
        test_succeeded=false
        cat <<-EOF
	ERROR: S3 file expansion not performed correctly:
	  Correct Contents of '$dir/$file':
	$(<./originals/$file)
	  Found Contents:
	$(<$dir/$file)

	EOF
      fi

      file="$dir"/"$file"
      test_check-perms test_succeeded "$file" 23 $(id -g) $(stat -c%a "$file")
    done

    dir="./p2comparedir"
    for file in $(ls $dir);do
      if ! diff ./originals/$file $dir/$file; then
        test_succeeded=false
        cat <<-EOF
	ERROR: S3 file expansion not performed correctly:
	  Correct Contents of '$dir/$file':
	$(<./originals/$file)
	  Found Contents:
	$(<$dir/$file)

	EOF
      fi

      file="$dir"/"$file"
      test_check-perms test_succeeded "$file" 24 25 $(stat -c%a "$file")
    done

    dir="./newdir/pcomparedir"
    for file in $(ls $dir);do
      if ! diff ./originals/$file $dir/$file; then
        test_succeeded=false
        cat <<-EOF
	ERROR: S3 file expansion not performed correctly:
	  Correct Contents of '$dir/$file':
	$(<./originals/$file)
	  Found Contents:
	$(<$dir/$file)

	EOF
      fi

      file="$dir"/"$file"
      test_check-perms test_succeeded "$file" 26 $(id -g) $(stat -c%a "$file")
    done

    dir="./newdir/p2comparedir"
    for file in $(ls $dir);do
      if ! diff ./originals/$file $dir/$file; then
        test_succeeded=false
        cat <<-EOF
	ERROR: S3 file expansion not performed correctly:
	  Correct Contents of '$dir/$file':
	$(<./originals/$file)
	  Found Contents:
	$(<$dir/$file)

	EOF
      fi

      file="$dir"/"$file"
      test_check-perms test_succeeded "$file" 27 28 $(stat -c%a "$file")
    done
  fi
else
  test_succeeded=false
fi

$test_succeeded
