#!/bin/bash
#
# Tests the expansion of environmental variables

export EXPAND_FILES="SIMPLE=./simple DIR=./newdir/luna NEWLINES=./newlines PERMSA=./perms1[464] PERMSB=./perms2[|23] PERMSC=./perms3[|24.25] PERMSD=./perms4[765|26] PERMSE=./perms5[341|27.28] FORGOT=./forgot"

export SIMPLE="Once upon a time..."
export DIR="The Cow Jumped Over the Moon!"
export NEWLINES="Bah, Bah, Black Sheep,Have you any wool?"
export PERMSA="Twice upon a time..."
export PERMSB="Thrice upon a time..."
export PERMSC="Dice upon a time..."
export PERMSD="Ice upon a time..."
export PERMSE="Mice upon a time..."
# FORGOT is intentionally not set


test_succeeded=true
if ! ../../s3-expand true; then # start s3-expand test
  test_succeeded=false
  echo "ERROR: s3-expand failed"
else


# Test first for creation
for file in ./simple ./newdir/luna ./newlines ./perms{1,2,3,4,5}; do
  if ! [[ -a $file ]]; then
    echo "$file was not created"
    echo
    test_succeeded=false
  fi
done

if [[ -a ./forgot ]]; then
  test_succeeded=false
  echo "File 'forgot' should not have been created."
  echo
fi


uid=$(id -u)
gid=$(id -g)

touch a
mode=$(stat -c%a a)
rm a

mkdir a
dmode=$(stat -c%a a)
rmdir a

test_check-perms test_succeeded "./simple"      $uid $gid $mode
test_check-perms test_succeeded "./newdir"      $uid $gid $dmode
test_check-perms test_succeeded "./newdir/luna" $uid $gid $mode
test_check-perms test_succeeded "./newlines"    $uid $gid $mode
test_check-perms test_succeeded "./perms1"      $uid $gid 464
test_check-perms test_succeeded "./perms2"      23   $gid $mode
test_check-perms test_succeeded "./perms3"      24   25   $mode
test_check-perms test_succeeded "./perms4"      26   $gid 765
test_check-perms test_succeeded "./perms5"      27   28   341

# Finally, test for contents, after resetting the modes
for file in ./simple ./newdir/luna ./newlines ./perms{1,2,3,4,5}; do
  chmod u+r $file
done

if ! [[ $SIMPLE == $(<./simple) ]]; then
  test_succeeded=false
  cat <<-EOF
	Simple environmental expansion not performed correctly:
	  Correct Contents:
	$SIMPLE
	  Found Contents:
	$(<./simple)

	EOF
elif ! [[ $DIR == $(<./newdir/luna) ]]; then
  test_succeeded=false
  cat <<-EOF
	New directory environmental expansion not performed correctly:
	  Correct Contents:
	$DIR
	  Found Contents:
	$(<./newdir/luna)

	EOF
elif ! [[ $(echo -n $NEWLINES |tr '\32' '\n') == $(<./newlines) ]]; then
  test_succeeded=false
  cat <<-EOF
	Newline environmental expansion not performed correctly:
	  Correct Contents:
	$(echo -n $NEWLINES | tr '\32' '\n')
	  Found Contents:
	$(<./newlines)

	EOF
elif ! [[ $PERMSA == $(<./perms1) ]]; then
  test_succeeded=false
  cat <<-EOF
	First permissions expansion not performed correctly:
	  Correct Contents:
	$PERMSA
	  Found Contents:
	$(<./perms1)

	EOF
elif ! [[ $PERMSB == $(<./perms2) ]]; then
  test_succeeded=false
  cat <<-EOF
	Second permissions expansion not performed correctly:
	  Correct Contents:
	$PERMSB
	  Found Contents:
	$(<./perms2)

	EOF
elif ! [[ $PERMSC == $(<./perms3) ]]; then
  test_succeeded=false
  cat <<-EOF
	Third permissions expansion not performed correctly:
	  Correct Contents:
	$PERMSC
	  Found Contents:
	$(<./perms3)

	EOF
elif ! [[ $PERMSD == $(<./perms4) ]]; then
  test_succeeded=false
  cat <<-EOF
	Fourth permissions expansion not performed correctly:
	  Correct Contents:
	$PERMSD
	  Found Contents:
	$(<./perms4)

	EOF
elif ! [[ $PERMSE == $(<./perms5) ]]; then
  test_succeeded=false
  cat <<-EOF
	Fifth permissions expansion not performed correctly:
	  Correct Contents:
	$PERMSE
	  Found Contents:
	$(<./perms5)

	EOF
fi

fi # end s3-expand test
$test_succeeded
